### ISSUE TITLE
ECG Data

### ISSUE THREAD

**Issue by zanovis** [kieranabrennan/every-breath-you-take#21]
Nice job on this app! I wanted to ask if you have plans to incorporate the ECG characteristics in the future, as I see the UUIDs are called out in the .py file. Thanks for any info!

**Comment by kieranabrennan** [comment]
@zanovis you'll see now I'm connecting to the sensors with a python package I've written that also has support for ECG
https://github.com/kieranabrennan/blehrm/blob/master/blehrm/clients/polar_h10.py
