### ISSUE TITLE
Specify python version

### ISSUE THREAD

**Issue by Hultner** [kieranabrennan/every-breath-you-take#22]
First I wanted to say great work on the app!

I tried this on python 3.12, 3.13 (with setuptools added), then I went all the way down to 3.9 with all failing on install. Finally I was able  to install it with python 3.11.

It would be very nice with some kind of note about this or even better a .python-version file for pyenv.

**Comment by kieranabrennan** [comment]
Thanks @Hultner. I've now tested it on 3.9 through to 3.12 with no trouble at all. I've updated the readme, added a .python-version file. Let me know if you have any further problems.
