### ISSUE TITLE
Info.plist must contain an NSBluetoothAlwaysUsageDescription

### ISSUE THREAD

**Issue by steni** [kieranabrennan/every-breath-you-take#9]
I'm trying to run on my Apple M1 Pro with macOS 13.4 (Ventura). I'm getting an error message:

```
Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.
```

I have tried packing the app up with py2app, but have not been successful.

**Comment by kbre93** [comment]
@steni try going into Settings > Privacy & Security > Bluetooth, and adding your terminal application or development environment to the list of applications that are allowed to use Bluetooth

**Comment by kbre93** [comment]
@steni did the suggestion above resolve your error?

**Comment by steni** [comment]
Yes it did. Thank you!
